### ISSUE TITLE
--download-game game:version seems not working

### ISSUE THREAD

**Issue by TurBoss** [spring/pr-downloader#105] opened 2017-09-17 00:38 UTC
Hello

I was trying to use pr-downloader to download a game with the --download-game option
seems to do nothing

```
$ ./pr-downloader --download-game chobby:stable
pr-downloader 0.7-387-g34f49e1
[Info] Using filesystem-writepath: /home/turboss/.spring
[Info] Free disk space: 381064 MB
[Info] Download complete!
```

and calling it without any options just the gamename

```
$ ./pr-downloader chobby:stable
pr-downloader 0.7-387-g34f49e1
[Info] Using filesystem-writepath: /home/turboss/.spring
[Info] Free disk space: 381140 MB
[Info] Found 34 repos in /home/turboss/.spring/rapid/repos.springrts.com/repos.gz

[Download] Chobby v0a.0.9.16
[Progress] 100% [==============================] 47370/47370 
[Info] Using rapid
[Info] http://chobby.repo.springrts.com/streamer.cgi?819465203712bffb5931f491aee8a40d
[Info] Download complete!======================] 74894323/74894323 
```

Thanks

**Comment by gajop** [comment] 2017-09-20 12:06
Duplicate of https://github.com/spring/pr-downloader/issues/101
What's your platform? It works fine on Linux

**Comment by TurBoss** [comment] 2017-09-23 12:35
Hello

my OS is ubuntu 17.04 x64

**Comment by gajop** [comment] 2017-09-23 12:53
Huh. That's bizarre, I'm also on Ubuntu and don't have issues (although maybe slightly different pr-downloader version.

**Closed** 2017-11-14 04:15 UTC
Labels: bug
